#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyContacts.Droid.Resource", IsApplication=true)]

namespace MyContacts.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Apu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bart = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ComicBookGuy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Homer = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Krusty = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Lisa = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Maggie = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Marge = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Milhouse = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int MoeSzyslak = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int MrBurns = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Placeholder = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int SideshowBob = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int WaylonSmithers = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int Email = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int EmailDetail = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Headshot = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int HeadshotDetail = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int Name = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int NameDetail = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int contactListView = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItemRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
